FROM nginx:1.13-alpine

COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY public /var/www/public
# docker build -f Dockerfile.nginx -t lbouquet/nginx-symf4 .
# docker login
# docker push lbouquet/nginx-symf4