
INSERT INTO tbl_language (id, english_name, native_name) VALUES
('ab', 'Abkhazian', 'Аҧсуа'),
('aa', 'Afar', 'Afar'),
('af', 'Afrikaans', 'Afrikaans'),
('ak', 'Akan', 'Akana'),
('sq', 'Albanian', 'Shqip'),
('am', 'Amharic', 'አማርኛ'),
('ar', 'Arabic', 'العربية'),
('an', 'Aragonese', 'Aragonés'),
('hy', 'Armenian', 'Հայերեն'),
('as', 'Assamese', 'অসমীয়া'),
('av', 'Avar', 'Авар'),
('ay', 'Aymara', 'Aymar'),
('az', 'Azerbaijani', 'Azərbaycanca / آذربايجان'),
('bm', 'Bambara', 'Bamanankan'),
('ba', 'Bashkir', 'Башҡорт'),
('eu', 'Basque', 'Euskara'),
('be', 'Belarusian', 'Беларуская'),
('bn', 'Bengali', 'বাংলা'),
('bh', 'Bihari', 'भोजपुरी'),
('bi', 'Bislama', 'Bislama'),
('bs', 'Bosnian', 'Bosanski'),
('br', 'Breton', 'Brezhoneg'),
('bg', 'Bulgarian', 'Български'),
('my', 'Burmese', 'Myanmasa'),
('km', 'Cambodian', 'ភាសាខ្មែរ'),
('ca', 'Catalan', 'Català'),
('ch', 'Chamorro', 'Chamoru'),
('ce', 'Chechen', 'Нохчийн'),
('ny', 'Chichewa', 'Chi-Chewa'),
('zh', 'Chinese', '中文'),
('cv', 'Chuvash', 'Чăваш'),
('kw', 'Cornish', 'Kernewek'),
('co', 'Corsican', 'Corsu'),
('cr', 'Cree', 'Nehiyaw'),
('hr', 'Croatian', 'Hrvatski'),
('cs', 'Czech', 'Česky'),
('da', 'Danish', 'Dansk'),
('dv', 'Divehi', 'ދިވެހިބަސް'),
('nl', 'Dutch', 'Nederlands'),
('dz', 'Dzongkha', 'ཇོང་ཁ'),
('en', 'English', 'English'),
('eo', 'Esperanto', 'Esperanto'),
('et', 'Estonian', 'Eesti'),
('ee', 'Ewe', 'Ɛʋɛ'),
('fo', 'Faroese', 'Føroyskt'),
('fj', 'Fijian', 'Na Vosa Vakaviti'),
('fi', 'Finnish', 'Suomi'),
('fr', 'French', 'Français'),
('gl', 'Galician', 'Galego'),
('lg', 'Ganda', 'Luganda'),
('ka', 'Georgian', 'ქართული'),
('de', 'German', 'Deutsch'),
('el', 'Greek', 'Ελληνικά'),
('kl', 'Greenlandic', 'Kalaallisut'),
('gn', 'Guarani', 'Avañe\'ẽ'),
('gu', 'Gujarati', 'ગુજરાતી'),
('ht', 'Haitian', 'Krèyol ayisyen'),
('ha', 'Hausa', 'هَوُسَ'),
('he', 'Hebrew', 'עברית'),
('hz', 'Herero', 'Otsiherero'),
('hi', 'Hindi', 'हिन्दी'),
('ho', 'Hiri Motu', 'Hiri Motu'),
('hu', 'Hungarian', 'Magyar'),
('is', 'Icelandic', 'Íslenska'),
('io', 'Ido', 'Ido'),
('ig', 'Igbo', 'Igbo'),
('id', 'Indonesian', 'Bahasa Indonesia'),
('ia', 'Interlingua', 'Interlingua'),
('ie', 'Interlingue', 'Interlingue'),
('iu', 'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ'),
('ik', 'Inupiak', 'Iñupiak'),
('ga', 'Irish', 'Gaeilge'),
('it', 'Italian', 'Italiano'),
('ja', 'Japanese', '日本語'),
('jv', 'Javanese', 'Basa Jawa'),
('kn', 'Kannada', 'ಕನ್ನಡ'),
('kr', 'Kanuri', 'Kanuri'),
('ks', 'Kashmiri', 'कश्मीरी / كشميري'),
('kk', 'Kazakh', 'Қазақша'),
('ki', 'Kikuyu', 'Gĩkũyũ'),
('ky', 'Kirghiz', 'Kırgızca / Кыргызча'),
('rn', 'Kirundi', 'Kirundi'),
('kv', 'Komi', 'Коми'),
('kg', 'Kongo', 'KiKongo'),
('ko', 'Korean', '한국어'),
('kj', 'Kuanyama', 'Kuanyama'),
('ku', 'Kurdish', 'Kurdî / كوردی'),
('lo', 'Laotian', 'ລາວ / Pha xa lao'),
('la', 'Latin', 'Latina'),
('lv', 'Latvian', 'Latviešu'),
('li', 'Limburgian', 'Limburgs'),
('ln', 'Lingala', 'Lingála'),
('lt', 'Lithuanian', 'Lietuvių'),
('lb', 'Luxembourgish', 'Lëtzebuergesch'),
('mk', 'Macedonian', 'Македонски'),
('mg', 'Malagasy', 'Malagasy'),
('ms', 'Malay', 'Bahasa Melayu'),
('ml', 'Malayalam', 'മലയാളം'),
('mt', 'Maltese', 'bil-Malti'),
('gv', 'Manx', 'Gaelg'),
('mi', 'Maori', 'Māori'),
('mr', 'Marathi', 'मराठी'),
('mh', 'Marshallese', 'Kajin Majel / Ebon'),
('mo', 'Moldovan', 'Moldovenească'),
('mn', 'Mongolian', 'Монгол'),
('na', 'Nauruan', 'Dorerin Naoero'),
('nv', 'Navajo', 'Diné bizaad'),
('ng', 'Ndonga', 'Oshiwambo'),
('ne', 'Nepali', 'नेपाली'),
('nd', 'North Ndebele', 'Sindebele'),
('se', 'Northern Sami', 'Sámegiella'),
('no', 'Norwegian', 'Norsk (bokmål / riksmål)'),
('nn', 'Norwegian Nynorsk', 'Norsk (nynorsk)'),
('oc', 'Occitan', 'Occitan'),
('oj', 'Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin'),
('cu', 'Old Church Slavonic / Old Bulgarian', 'словѣньскъ / slověnĭskŭ'),
('or', 'Oriya', 'ଓଡ଼ିଆ'),
('om', 'Oromo', 'Oromoo'),
('os', 'Ossetian / Ossetic', 'Иронау'),
('pi', 'Pali', 'Pāli / पाऴि'),
('pa', 'Panjabi / Punjabi', 'ਪੰਜਾਬੀ / पंजाबी / پنجابي'),
('ps', 'Pashto', 'پښتو'),
('fa', 'Persian', 'فارسی'),
('ff', 'Peul', 'Fulfulde'),
('pl', 'Polish', 'Polski'),
('pt', 'Portuguese', 'Português'),
('qu', 'Quechua', 'Runa Simi'),
('rm', 'Raeto Romance', 'Rumantsch'),
('ro', 'Romanian', 'Română'),
('ru', 'Russian', 'Русский'),
('rw', 'Rwandi', 'Kinyarwandi'),
('sm', 'Samoan', 'Gagana Samoa'),
('sg', 'Sango', 'Sängö'),
('sa', 'Sanskrit', 'संस्कृतम्'),
('sc', 'Sardinian', 'Sardu'),
('gd', 'Scottish Gaelic', 'Gàidhlig'),
('sr', 'Serbian', 'Српски'),
('sh', 'Serbo-Croatian', 'Srpskohrvatski / Српскохрватски'),
('sn', 'Shona', 'chiShona'),
('ii', 'Sichuan Yi', 'ꆇꉙ / 四川彝语'),
('sd', 'Sindhi', 'सिनधि'),
('si', 'Sinhalese', 'සිංහල'),
('sk', 'Slovak', 'Slovenčina'),
('sl', 'Slovenian', 'Slovenščina'),
('so', 'Somalia', 'Soomaaliga'),
('nr', 'South Ndebele', 'isiNdebele'),
('st', 'Southern Sotho', 'Sesotho'),
('es', 'Spanish', 'Español'),
('su', 'Sundanese', 'Basa Sunda'),
('sw', 'Swahili', 'Kiswahili'),
('ss', 'Swati', 'SiSwati'),
('sv', 'Swedish', 'Svenska'),
('tl', 'Tagalog / Filipino', 'Tagalog'),
('ty', 'Tahitian', 'Reo Māohi'),
('tg', 'Tajik', 'Тоҷикӣ'),
('ta', 'Tamil', 'தமிழ்'),
('tt', 'Tatar', 'Tatarça'),
('te', 'Telugu', 'తెలుగు'),
('th', 'Thai', 'ไทย / Phasa Thai'),
('bo', 'Tibetan', 'བོད་ཡིག / Bod skad'),
('ti', 'Tigrinya', 'ትግርኛ'),
('to', 'Tonga', 'Lea Faka-Tonga'),
('ts', 'Tsonga', 'Xitsonga'),
('tn', 'Tswana', 'Setswana'),
('tr', 'Turkish', 'Türkçe'),
('tk', 'Turkmen', 'Туркмен / تركمن'),
('tw', 'Twi', 'Twi'),
('uk', 'Ukrainian', 'Українська'),
('ur', 'Urdu', 'اردو'),
('ug', 'Uyghur', 'Uyƣurqə / ئۇيغۇرچە'),
('uz', 'Uzbek', 'Ўзбек'),
('ve', 'Venda', 'Tshivenḓa'),
('vi', 'Vietnamese', 'Tiếng Việt'),
('vo', 'Volapük', 'Volapük'),
('wa', 'Walloon', 'Walon'),
('cy', 'Welsh', 'Cymraeg'),
('fy', 'West Frisian', 'Frysk'),
('wo', 'Wolof', 'Wollof'),
('xh', 'Xhosa', 'isiXhosa'),
('yi', 'Yiddish', 'ייִדיש'),
('yo', 'Yoruba', 'Yorùbá'),
('za', 'Zhuang', 'Cuengh / Tôô / 壮语'),
('zu', 'Zulu', 'isiZulu');
