apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: php-fpm
  name: php-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php-fpm
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: php-fpm
    spec:
      containers:
      - env:
        - name: ADMIN_EMAIL_ADDRESS
          value: admin@domain.tld
        - name: APP_ENV
          value: dev
        - name: APP_SECRET
          value: 692984a0f492b64a2c7733f8e742b2bb
        - name: DATABASE_URL
          value: mysql://joliquiz:db_password@database:3306/joliquiz
        - name: LOCALE
          value: en
        - name: MAILER_URL
          value: null://localhost
        image: lbouquet/joliquiz-php
        imagePullPolicy: ""
        name: php-fpm
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
